$schema: schema/config.schema.json
server:
  name: my_server
  keepalive: 30
  mounts:
    - /: out
  mappings:
    - /: index.html
  friendly_responses:
    - 404: /out/404.html
  services:
    - ip: 127.0.0.1
      port: 80
    - ip: 127.0.0.1
      port: 443
      cert-file: tls/www.example.com.crt
      pkey-file: tls/www.example.com.pem