$schema: schema/config.schema.json
server:
  name: my_server
  keepalive: 30
  mounts:
    - /: out
  mappings:
    - /: index.html
  friendly_responses:
    - 404: /out/404.html
  services:
    - ip: 127.0.0.1
      port: 80