$schema: schema/config.schema.json
server:
  name: my_server
  keepalive: 30
  mounts:
    - www: out
  services:
    - threads: 4
      cert-file: xxx.crt
      pkey-file: xxx.pem
      ip: 0.0.0.0
      port: 443
    - threads: 2
      ip: 127.0.0.1
      port: 80
