stages:
  - build

nodejs:
  stage: build
  image: node:20
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - out
    expire_in: 1 hour

cmake:
  stage: build
  image: kuyoh/vcpkg
  variables:
    VCPKG_DEFAULT_BINARY_CACHE: $CI_PROJECT_DIR/vcpkg-archives
  cache:
    key:
      files:
        - vcpkg.json
        - vcpkg-ports/**
    paths:
      - vcpkg-archives
  script:
    - cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
    - cmake --build build --target Hexagon
  artifacts:
    paths:
      - build/Hexagon
    expire_in: 1 hour

package:
  stage: build
  when: always
  dependencies:
    - nodejs
    - cmake
  needs:
    - nodejs
    - cmake
  script:
    - mkdir -p App
    - cp build/Hexagon App/Hexagon
    - cp -r tls App/tls
    - cp -r config.yml App/config.yml
    - cp -r out /App/out
  artifacts:
    paths:
      - App
    expire_in: 30 days