stages:
  - build

nodejs:
  stage: build
  image: node:20
  cache:
    key:
      files:
        - package.json
        - package-lock.json
    paths:
      - node_modules
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - out
    expire_in: 1 hour

cmake:
  stage: build
  image: kuyoh/vcpkg
  cache:
    key:
      files:
        - vcpkg.json
        - vcpkg-ports/**
    paths:
      - $HOME/.cache/vcpkg/archives
  script:
    - cmake -Bbuild -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake
    - cmake --build build --target Hexagon
  artifacts:
    paths:
      - build/Hexagon
    expire_in: 1 hour

package:
  stage: build
  when: always
  image: python:3.11
  dependencies:
    - nodejs
    - cmake
  needs:
    - nodejs
    - cmake
  script:
    - apt update
    - apt install fuse3 -yq
    - python3 ./scripts/package_appimage.py
  artifacts:
    paths:
      - ./*.AppImage
    expire_in: 30 days